image: node:18

stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: screen-show
  DOCKER_TAG: ${CI_COMMIT_SHA}

cache:
  paths:
    - node_modules/

before_script:
  - npm install

test:
  stage: test
  script:
    - npm test
  only:
    - merge_requests
    - main

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest
  only:
    - main

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - echo "Deploying to production..."
    # Add your deployment commands here
    # For example:
    # - kubectl apply -f k8s/deployment.yaml
  environment:
    name: production
  only:
    - main 